### ISSUE TITLE
Lambda not writing to s3 and therefore 404 error

### ISSUE THREAD

**Issue by goochi1** [awslabs/voice-powered-analytics#5]
Hey i am going through this workshop and when i copy in the lambda, fill out the env and provided and get the bucket from the stack i get:
```

errorMessage": "An error occurred (404) when calling the HeadObject operation: Not Found",
  "errorType": "ClientError",
```
When it is trying to 's3_client.download_file(s3_bucket, s3_key[1:], "/tmp/results.csv")'

I looked in the bucket and there is no data in there which is correct. 

it seems the athena output location isnt working. Can you help please

**Comment by aemilcar** [comment]
Can you tell me what step you are in the process where this error happens so I can reproduce it myself?

**Comment by goochi1** [comment]
Hi it was when i tried running the given lambda function

**Comment by emilcara** [comment]
Which region are you running out of and did you perform module 0, build your own data lake or did you go straight to module 1? This will allow me to narrow down where the error may be coming from.

**Comment by goochi1** [comment]
I went stright to 1 as said 0 wasnt needed

**Comment by emilcara** [comment]
No problem. I just needed that to know where to start troubleshooting. And which region?

**Comment by AndreyStille** [comment]
Please help
How did you solve your issue?
