### ISSUE TITLE
Tried doing this for my own data but cant seem to pickup the 2nd question

### ISSUE THREAD

**Issue by goochi1** [awslabs/voice-powered-analytics#6]
Hi again, 

So after the success of the last one i wanted to run this against my data sets with my own questions.
However when i get to the last stay of asking the Alexa she can find my skill but not answer the question 'whats my <slot value>' .
the 1st lambda works and the alexa can find my skill but its the specific question it dosent like.
Would you guys be able to help? not sure what specifics you need to solve this as i I have changed the name and she responses with
 'There was a problem with the requested skill's response'

**Comment by goochi1** [comment]
HI is there any update with this or any help available?

**Comment by aemilcar** [comment]
It sounds like your backend Lambda function maybe is causing an error. If you look at your logs for those invocations, what errors are you seeing?

**Comment by goochi1** [comment]
When i run the athena_poller the lambda is successful, that the one you mean?

**Comment by aemilcar** [comment]
No. The Lambda function for the skill itself. It should be VPA-Setup-AlexaMetricSkill-<random-ID>

**Comment by goochi1** [comment]
Ah yes i see, will investigate more and come back if i have an issue. Thanks!!!

**Comment by goochi1** [comment]
So i redeployed it all and am getting back:
'The value for reinvent twitter sentiment is -1'

I changed my query to my own table so conused what the -1 means. 

Aslo when i Look at my out out on the vpa_lambda_athena_poller i get:
[ERROR]	2020-02-02T12:14:57.339Z	871063fc-e5a1-451b-b1e1-5f4cf983d585	ERROR: Failed to write metric to DDB

**Comment by goochi1** [comment]
Hi i rebuilt it all and seems to be working.
Do you guys have any guides for adding multiple athena queries?

**Comment by goochi1** [comment]
Actully follow on, I added a slot and added the value into the dynamo but when i ask alexa it just comes back with -1. any ideas?
