### ISSUE TITLE
Query Error in Athena

### ISSUE THREAD

**Issue by inehalsharma** [awslabs/voice-powered-analytics#7]
Hi,
I tried to run the query to create a table in Athena using this code:
CREATE EXTERNAL TABLE IF NOT EXISTS default.tweets(
  id bigint COMMENT 'Tweet ID', 
  text string COMMENT 'Tweet text', 
  created timestamp COMMENT 'Tweet create timestamp', 
  screen_name string COMMENT 'Tweet screen_name',
  screen_name_followers_count int COMMENT 'Tweet screen_name follower count',
  place string COMMENT 'Location full name',
  country string COMMENT 'Location country',
  retweet_count int COMMENT 'Retweet count', 
  favorite_count int COMMENT 'Favorite count')
ROW FORMAT SERDE 
  'org.openx.data.jsonserde.JsonSerDe' 
WITH SERDEPROPERTIES ( 
  'paths'='id,text,created,screen_name,screen_name_followers_count,place_fullname,country,retweet_count,favorite_count') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://aws-vpa-tweets/tweets/'

I changed the location according to Ireland but when I run the query in the query editor in Athena, I get the following error:

Your query has the following error(s):

Unable to verify/create output bucket aws-vpa-tweets-euw1 (Service: AmazonAthena; Status Code: 400; Error Code: InvalidRequestException; Request ID: 890390cf-1db9-40d3-9259-ba7798be20dd)

**Comment by emilcara** [comment]
Hi Nehal,

It seems that either the bucket doesn’t exist, or you don’t have the proper permissions. Try this link out and let me know what happens and I’ll help troubleshoot further.

https://aws.amazon.com/premiumsupport/knowledge-center/athena-output-bucket-error/

Thanks,

Alex


On Aug 4, 2020, at 3:02 PM, Nehal Sharma <notifications@github.com> wrote:

﻿

Hi,
I tried to run the query to create a table in Athena using this code:
CREATE EXTERNAL TABLE IF NOT EXISTS default.tweets(
id bigint COMMENT 'Tweet ID',
text string COMMENT 'Tweet text',
created timestamp COMMENT 'Tweet create timestamp',
screen_name string COMMENT 'Tweet screen_name',
screen_name_followers_count int COMMENT 'Tweet screen_name follower count',
place string COMMENT 'Location full name',
country string COMMENT 'Location country',
retweet_count int COMMENT 'Retweet count',
favorite_count int COMMENT 'Favorite count')
ROW FORMAT SERDE
'org.openx.data.jsonserde.JsonSerDe'
WITH SERDEPROPERTIES (
'paths'='id,text,created,screen_name,screen_name_followers_count,place_fullname,country,retweet_count,favorite_count')
STORED AS INPUTFORMAT
'org.apache.hadoop.mapred.TextInputFormat'
OUTPUTFORMAT
'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
's3://aws-vpa-tweets/tweets/'

I changed the location according to Ireland but when I run the query in the query editor in Athena, I get the following error:

Your query has the following error(s):

Unable to verify/create output bucket aws-vpa-tweets-euw1 (Service: AmazonAthena; Status Code: 400; Error Code: InvalidRequestException; Request ID: 890390cf-1db9-40d3-9259-ba7798be20dd)

**Comment by inehalsharma** [comment]
It worked.Thanks for your timely help:)
